import { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import Script from 'next/script'; // 1. Import the Script component
import "./globals.css";

export const metadata: Metadata = {
  title: "Ouiboo",
  description: "Generated by Ouiboo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {   
  return (
    <html lang="en">
      {/* 2. The <head> tag is now managed by Next.js metadata and is not needed here */}
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>

      {/* 3. Add the Google Analytics scripts here using the next/script component */}
      <Script
        strategy="afterInteractive"
        src="https://www.googletagmanager.com/gtag/js?id=G-NGNWG1877Q"
      />
      <Script
        id="google-analytics"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-NGNWG1877Q');
          `,
        }}
      />
    </html>
  );
}