// layout.js
import { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import Script from 'next/script';
import "./globals.css";
import TranslationsProvider from "../components/TranslationsProvider";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Ouiboo",
  description: "Generated by Ouiboo",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
        <TranslationsProvider>
          <Suspense fallback={<div>Loading...</div>}>
            {children}
          </Suspense>
        </TranslationsProvider>
        
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-NGNWG1877Q"
        />
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-NGNWG1877Q');
            `,
          }}
        />
      </body>
    </html>
  );
}